- README.md
It appeared the 'strange' sentence with <cmath> was caused by the bare '<', which is solved by using `<cmath>`,which probably was intended  anyway.
> Fix markdown by avoiding bare <cmath>

- include/units.h
Trying to compile on GCC-ARM 5.4.1, the `#pragma warning` generates a warning that the pragma is being ignored, presumably because this only applies to MSVC. I've corrected the existing typo and added another check for the macro actually being defined. This gets rid of the warnings related to the pragma.
Note though I'm still unable to build on GCC-ARM due to unrelated errors/warnings which I'll be fixing later.
> Fix typo _MCS_VER -> _MSC_VER and only add pragma warning when it's actually defined

- include/units.h
This allows usage of this library in projects that compile with -std=c++14 -Wall -Wextra -pedantic. Tested on GCC 6.2.1.
> Fix -Wpedantic warnings

- include/units.h
- unitTests/main.cpp
The MACRO definitions that generate the unit types were updates to support adding units with or without IO, and with or without literals. This also allows to support different compilers (or compiler versions) by enabling/disabling these macros. 
Literals are implemented using a `make_unit<T>(value)` function to construct a unit from a plain double. This seems to be a useful function on its own, as it ensures the user has to explicitly provide the type right next to the plain value, which is not necessarily the case when using an (explicit) constructor (for example in member initialization).
> Change MACRO definitions to support adding units with/without IO/literals. Unify VS versions.

- README.md
- include/units.h
Various spelling corrections.
File units.h contains a series of statements like 
>The SI unit for voltage is `volts`,...*.
I'd  be inclined to write: 
>The SI unit for voltage is `volt`,...*.
i.e. using a singular <strike>capitalized</strike> unit <strike>where required</strike>.
Perhaps it's nice to add the following reference to Readme: 
Ambler Thompson and Barry N. Taylor. [Guide for the Use of the International System of Units (SI)](http://physics.nist.gov/cuu/pdf/sp811.pdf). NIST Special Publication 811 2008 Edition.
> Fix spelling in Readme and units.h documentation

- include/units.h
New try for [the same issue](https://github.com/nholthaus/units/pull/72)
So here am I :)
Sorry for the inconvenience, my editor automatically removes all whitespace from end of the line - seems as you had much of it.
> add inline to pow() and abs() for different compilation units #2

- include/units.h
Fix the warning 'conversion from "long double" to "const double", possible loss of data' in VS2015. This warning is only shown, when compiling with "/W4"
> Fix compiler warning C4244

- CMakeLists.txt
To have cmake install units library to a local 'install' directory:
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="install" ..
cmake --build . --target install
The units library can then be used in some other cmake project using the
standard
'find_package' command. Like so:
find_package(units)
> added support for cmake install

- CMakeLists.txt
- README.md
#91 
I had an old branch as subdirectory in my project, sorry for the misleading issue. Added a few lines to the readme better explaining how to use find_package, and added a namespace to the exported target in order to avoid conficts with user targets.
> Add namespace to exported target

- include/units.h
When using clang with `-Wall` and `-Wextra` it complains because of unused parameters.
Since the parameter do not get used with any configuration I removed the parameter names instead of using the attribute `[[maybe_unused]]`.
> Remove an unused parameter warning for clang

- CMakeLists.txt
#94 Now cmake generates a unitsConfigVersion.cmake file to suport `find_package(units 2.3.1 REQUIRED)` with same major version compatibility :)
> Units version file

- include/units.h
- unitTests/main.cpp
Resolves #125.
Along the way, some of the supporting traits and other utilities might need to be changed to support mixed underlying types.
> Support integral underlying types

- include/units.h
- unitTests/main.cpp
Makes the units hashable. I took the liberty of making it `constexpr` rather than not and using the `std::hash` of the underlying type.
Drive-by fix: remove `CompileTimeArithmetic` test ?scope? I think it predates `constexpr` units.
> Add std::hash specialization

- include/units.h
- unitTests/main.cpp
I noticed that hashing floating-point units didn't meet [this requirement](https://wg21.link/hash.requirements#2.sentence-9). I took the easy way out of using the non-`constexpr` `std::hash<`_floating-point_`>` in that case.
> Hash fixes

- include/units.h
When the conversion to the base unit is lossy, it is a compile-time error.
This solution might incur accuracy loss as the unit is
converted to a base unit of `double` underlying type.
Any idea on how to avoid the accuracy loss?
> Fix streaming of ephemeral units of integer underlying type

- include/units.h
- include/units/core.h
- include/units/time.h
- unitTests/main.cpp
Resolves #160 to prevent having to prefix the `unit_conversion` tags everywhere so that they're valid outside their namespace [here](https://github.com/nholthaus/units/compare/v3.x...johelegp:strong_type_alias?expand=1#diff-cc75003c399d878c360873c2c8c783d6R152).
The new type trait, `strong`, maps a `unit_conversion` to its strong type alias. They are used as late as possible to prevent ODR issues. Manipulators like `squared` don't use it as they're used in the definition of units. See, for example:
```C++
UNIT_ADD(solid_angle, degree_squared, degrees_squared, sq_deg, squared<angle::degrees>)
```
This declares `degrees_squared` as a strong type alias of `squared<angle::degrees>`, and then specializes `strong` so that `strong_t<squared<angle::degrees>>` names `degrees_squared`. If `squared` …
> `unit_conversion`s as strong type aliases

- include/units/core.h
- unitTests/main.cpp
- Change term of non-linear scale to numerical scale. Suggested in https://github.com/nholthaus/units/issues/185#issuecomment-423107386.
- Add `linearized_value_t` tag to disambiguate the `unit` constructor whose value is already linearized.
- Reduce the scales' scope of functionality to what their name suggest. Make them non-template entities with only a `linearize` and `scale` static member functions in place of their old constructor and `operator()` respectively. Move `m_value` and `operator()` to `unit`, where they naturally belong.
- `unit` still inherits from `NumericalScale`, but privately. This is so that the [scale traits](https://github.com/nholthaus/units/blob/5483589322daad285eedd4e2822058ba4e6640d8/include/units/core.h#L2718-L2754) continue to work.
- Rename `m_value` to …
> Simplify numerical scales

- include/units/core.h
- unitTests/main.cpp
I found it weird when I first read its declaration, as I'd expect it to be `dimension_divide<data, time>` and not `make_dimension<data, std::ratio<-1>>` like `frequency` is to `time`. Earlier, I finally tried to mix a data transfer unit with a time unit, and chaos ensued.
> Fix data transfer rate unit's dimension

- include/units/core.h
Include correct header.
Prefix with `std::`.
> Fix `<clocale>` use

- include/units/core.h
Superseded by units parametrized over the underlying type.
The `UNIT_ADD_CUSTOM_TYPE_UNIT_DEFINITION` macro it uses has already been removed, but I missed this one.
> Remove `UNIT_ADD_WITH_CUSTOM_TYPE`

- include/units/core.h
That is, convert to the underlying type in the caller.
> Handle assignment from arithmetic type like compound assignment

- include/units/core.h
Prefer `std::enable_if_t<..., int> = 0`
to `class = std::enable_if_t<...>`
as it works more generally.
> Normalize `std::enable_if_t` usage in template parameter lists

- include/units.h
- include/units/core.h
- unitTests/main.cpp
in the spirit of our other namespace inlining, I'm inlining the constants namespace as well
> inline namespace constants

- include/units/core.h
This prevent the use of the return type in the function signature and return statement from desynchronizing. With the upcoming changes, such desynchronization would cause a temporary to be used to construct the actual return type.
The return types of the return statements were more readable than those of the function signature, as we used type aliases local to the functions. I didn't want to change the function signatures as that might be visible in the doxygen-generated documentation.
> DRY in return types

- include/units/core.h
- unitTests/main.cpp
- Mostly removes uses of the word container in unit containers and updates code/comments based on `conversion_factor` renaming.
- Renames `is_convertible_conversion_factor` to `is_same_dimension` as per https://github.com/nholthaus/units/issues/185#issuecomment-423004260.
- ~~Adds `store_linear_value_t` tag type, as per https://github.com/nholthaus/units/issues/185#issuecomment-423350563. `unit` still forwards extra arguments to the scale, but `units`' scales now only know about `store_linear_value_t`~~.
> Documentation improvements

- include/units/core.h
- unitTests/main.cpp
I didn't consider these specializations back then. While further testing [my quantity concepts](https://github.com/johelegp/Made_in_Abyss/blob/master/doc/concepts.md#quantities-conceptsobjectqty), I tested whether the dimensionless units and arithmetic types behaved like quantities of the same dimension, and it failed. I don't know if it's the cause, but I realized that there weren't `std::common_type` specializations for dimensionless units and arithmetic types, unlike how there are ordering and arithmetic operators for them. You'll see that, in the test I added in this PR, there are inconsistencies in the common type. Some are dimensionless units, other are arithmetic types.
> Fix common type of dimensionless and arithmetic types

- include/units/core.h
- unitTests/main.cpp
For the longest while, I've been trying to fix and improve the type traits. Since success eludes me, I'm going to push what I can. Slowly, but eventually, that should improve the situation.
[`UnaryTypeTrait`](https://timsong-cpp.github.io/cppwp/n4659/meta.rqmts#def:UnaryTypeTrait).
> Teach `is_`x`_unit` to be a `UnaryTypeTrait`

- include/units/core.h
- unitTests/main.cpp
Partially addresses #185. The changed tests from the first commit were suffering from the `std::is_same_v<void, void>` syndrome.
> Fix `is_convertible_unit` and `is_same_dimension`

- CMakeLists.txt
- include/units.h
- include/units/core.h
- unitTests/main.cpp
resolves #219.
Refs: 1634c7864d782e9ef960e73a45a376a4b728ca30
This ICEs on GCC 10+ due to [GCC 95486](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95486). So it may be incomplete.
> revert: strong units

- include/units.h
I noticed that the constexpr Pi overloads (and branches for v3.x) don't assign the result of `pow` to a `constexpr` variable, which might result in the calls actually being performed at runtime for implementations less eager to do stuff at compile time.
> Convert optimizations backport

- CMakeLists.txt
Previously used `target_compile_definitions()` added `-D/permissive-` flag instead.
> Use `target_compile_options()` to add `/permissive-` flag

- CMakeLists.txt
The current `CMakeLists.txt` adds `"/permissive-"` as a `target_compile_definitions`. However it is a flag not a compile definition, see here https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=vs-2017
> Fix setting of permissive-

- include/units.h
These two functions can be safely marked ``constexpr``.
At present, if you try to write:
```
constexpr meter_t x = -1_m;
```
you get an error.
This PR fixes this.
> Make unarary ``operator+()`` and ``operator-()`` ``constexpr``

- .travis.yml
- appveyor.yml
- include/units.h
- unitTests/main.cpp
Return values of arithmetic operators were not constexpr. So all containers with negative literals may fail on compile time. This patch should fix this behaviour.
> Operator constexpr

- include/units/core.h
Working towards correct `std::common_type` specializations. First, put everything in one place.
> Add common type of time units and `std::chrono::duration`

- include/units/core.h
The pow() overload taking an unsigned second parameter was
declared/defined after it was used in the other pow() implementation.
This results in compilation errors [0]. Moving the unsigned overload
above the signed overload fixes the issue.
[0]:
awang@rp units % cat test.cpp
int main() {}
awang@rp units % clang++ -I include/ -std=c++17 test.cpp
In file included from test.cpp:1:
In file included from include/units.h:50:
In file included from include/units/acceleration.h:49:
In file included from include/units/length.h:49:
include/units/core.h:1710:64: error: call to function 'pow' that is neither visible in the template definition nor
found by argument-dependent lookup
return y == 0 ? 1.0 : (y < 0 ? 1.0 / x * pow(x, y + 1) : x * pow(x, static_cast<unsigned lon...
^ …
> Swap pow()s

- include/units/core.h
This has a little bit of cleaning up my previous pow() PR and also adds a pow() that uses a compile-time exponent.
> pow() tweaks and a compile-time pow()

- include/units/core.h
Removing trailing zeros when using integer containers led to incorrect string representations:
```to_string(meter<int>(1000)) --> 1 m```
> remove trailing zeros only if the container is a floating point type

- include/units.h
- unitTests/main.cpp
As reported in issue #284, some functions produce incorrect results when
passed certain dimensionless quantites. For example, this program from
the issue, slightly modified for brevity and to try to make a later
point clearer:
#include "units.h"
#include <iostream>
#include <cmath>
using namespace units::literals;
int main()
{
const auto c = 1.0_um * (-1 / 1.0_m);
std::cout << "c                   : " << c << std::endl ;
std::cout << "units::math::exp(c) : " << units::math::exp(c) << std::endl ;
std::cout << "std::exp(c.value()) : " << std::exp(c.value()) << std::endl ;
return EXIT_SUCCESS ;
}
Outputs:
c                   : -1e-06
units::math::exp(c) : 0.367879
std::exp(c.value()) : 0.999999
value() is basically to<>(), but with the template parameter hard-coded
to underlying_type, and …
> Fix incorrect math function output for scaled dimensionless types

- include/units.h
Hi!
Recently I compiled `units` with `DISABLE_PREDEFINED_UNITS=ON` but could not access `contants::PI` despite `ENABLE_PREDEFINED_CONSTANTS_UNITS=ON`.
It seems this problem has been reported in #264. Could the fix be that simple?
> Fix "ENABLE_PREDEFINED_CONSTANTS_UNITS" not used (#264)

- CMakeLists.txt
When adding `units` to a **CMake** project using **FetchContent**, testing has to be explicitly disabled.
This check only enables testing, if `units` is the main project being built.
The **ALIAS** target makes sure, that `units` can be linked as `units::units` not only from the install tree, but from the build tree as well.
Both of these changes enable the cleaner usage of `units` with **FetchContent**.
```
FetchContent_Declare(
nholthaus_units
GIT_REPOSITORY https://github.com/nholthaus/units.git
GIT_TAG master)
set(BUILD_TESTS OFF)
FetchContent_MakeAvailable(nholthaus_units)
if(NOT TARGET units::units)
add_library(units::units ALIAS units)
endif()
```
```
FetchContent_Declare(
nholthaus_units
GIT_REPOSITORY https://github.com/nholthaus/units.git
GIT_TAG master) …
```
> Add MAIN_PROJECT check for test option

- CMakeLists.txt
A few variables prefixed with UNITS_ are defined to control various
build options, but prefix-less versions are checked in the rest of the
file when determining their values. This makes the options effectively
useless.
This commit unifies definition and use so the options actually affect
the build.
> Fix UNITS_<VAR> def and <var> use mismatch

- include/units/core.h
Fix ambiguous parse error in the following expression:
if constexpr (PiRatio::num / PiRatio::den < 1 && PiRatio::num / PiRatio::den > -1)
GCC-12 apparently interprets `PiRatio::den < 1 && PiRatio::num / PiRatio::den >` as a template expression, which it shouldn't. Help disambiguating this expression by putting parentheses around the division.
Closes #306
> Fix compile error under GCC-12

- CMakeLists.txt
From <https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html>:
> Changed in version 3.27: Compatibility with versions of CMake older than 3.5 is deprecated. Calls to cmake_minimum_required(VERSION) or cmake_policy(VERSION) that do not specify at least 3.5 as their policy version (optionally via ...<max>) will produce a deprecation warning in CMake 3.27 and above.
> Updated CMake policy version to resolve deprecation warning.

- include/units.h
- unitTests/main.cpp
Extended std::numeric_limits class with some functions needed to use it with yaml-cpp.
> Some numeric_limits and numeric helper functions were missing

- include/units.h
Some other libraries define PI, which creates a conflict. This will implicitly resolve this problem. (It can be resolved explicitly, by adding this line of code before include, but that's extremely annoying)
> Add #undef PI

- include/units/core.h
- unitTests/main.cpp
Ensures sizof(unit type) is the same as sizeof(underlying_type), which was not the case on Windows on the v3.x branch.
Without that fix I observed sizeof(meters<float>) to be 8  as each units base class contributes at least one byte on top of the 4 bytes of a float.
According to [this answer](https://stackoverflow.com/a/55530422/4249338), that fix is valid since Visual Studio 2017 Update 2, which seems acceptable to me in term of backward compatibility for the new branch? 
Extended test coverage accordingly.
> MSVC-specific Empty Baseclass Optimization activation.

- include/units/length.h
A mil was defined as 1000 inches instead of 1/1000 inches.
> Fix mil definition

- include/units.h
The update fixes https://github.com/nholthaus/units/issues/308.
> Using intmax_t instead of size_t fixes narrowing conversion on 32bit

- include/units.h
- unitTests/main.cpp
> fix (backport): define mil as 1/1000 of an inch and not 1000 inches
